export const BEGIN_AJAX_CALL = "BEGIN_AJAX_CALL";
export const AJAX_CALL_ERROR = "AJAX_CALL_ERROR";

export const FORM_SUBMIT = "FORM_SUBMIT";
export const FORM_SUBMIT_SUCCESS = "FORM_SUBMIT_SUCCESS";
export const FORM_SUBMIT_FAIL = "FORM_SUBMIT_FAIL";
export const FORM_RESET = "FORM_RESET";
export const FORM_SUBMIT_MISSING_FIELDS = "FORM_SUBMIT_MISSING_FIELDS";
